#ifndef SCREENSTATES_H
#define SCREENSTATES_H

enum ScreenState {
    START_SCREEN,
    MAIN_MENU,
    READ_FREQUENCIES_MENU,
    READ_NFC_INFO_SCREEN,
    READ_NFC_LOADING_SCREEN,
    NFC_INFO_SCREEN,
    NFC_MESSAGE_SCREEN,
    NFC_READ_OPTIONS_MENU,
    CRACKING_SCREEN,
    READ_RFID_INFO_SCREEN,
    LOW_FREQ_READ
};

#endif
